spring:
 application:
  name: mbasket-shop-mvc
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
 datasource:
#  url: jdbc:mysql://localhost:3306/mbasketdb
  URL: jdbc:mysql://mbasketdb.c3aegiqqe5kx.us-east-1.rds.amazonaws.com:3306/mbasketdb
  username: mbasketuser
  password: mbasketpwd
# Enables automatic execution of schema.sql and data.sql
  initialization-mode: always
  schema: classpath:schema.sql
  data: classpath:data.sql 
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
 mvc:
  static-path-pattern: /mbasketImages/**

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server:
 port: 8081
 servlet:
  context-path: /mbasket

eureka:
 client:
  serviceURL:
   defaultZone: http://${EUREKA_SERVER_IP:localhost}:8761/eureka

#management:
# tracing:
#  enabled: true
#  sampling:
#   probability: 1.0
# zipkin:
#  tracing:
#   endpoint: http://localhost:9411/api/v2/spans

