spring:
 application:
  name: mbasket-service-gateway
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
   routes:
    - id: mbasketmvc
      uri: lb://mbasket-shop-mvc
      predicates:
      - Path=/mbasket/**
    - id: mbasketmvcinternalredirect
      uri: lb://mbasket-shop-mvc
      predicates:
      - Path=/**
      filters:
#            - AddRequestHeader=Host, gateway-url.com
      - RewriteLocationResponseHeader=AS_IN_REQUEST, http://host.docker.internal:8081, http://localhost:8080
server:
 port: 8080

eureka:
 client:
  serviceURL:
   defaultZone: http://localhost:8761/eureka

management:
 endpoint:
  gateway:
   enabled: true
 endpoints:
  web:
   exposure:
    include: gateway
 tracing:
  enabled: true
  sampling:
   probability: 1.0
 zipkin:
  tracing:
   endpoint: http://localhost:9411/api/v2/spans


